### ISSUE TITLE
setools fails to build with cython 0.29.21 and Python 3.9

### ISSUE THREAD

**Issue by fishilico** [SELinuxProject/setools#54]
Hi,
When building setools (4.3.0 and `master` branch) on an up-to-date Arch Linux system, I now get many errors such as:
```text
setools/policyrep.c: In function ‘__pyx_pf_7setools_9policyrep_6AVRule_9statement’:
setools/policyrep.c:92274:3: error: ‘_PyUnicode_get_wstr_length’ is deprecated [-Werror=deprecated-declarations]
92274 |   __pyx_t_1 = (__pyx_v_self->__pyx_base.rule_string != Py_None)&&(__Pyx_PyUnicode_IS_TRUE(__pyx_v_self->__pyx_base.rule_string) != 0);
      |   ^~~~~~~~~
In file included from /usr/include/python3.9/unicodeobject.h:1026,
                 from /usr/include/python3.9/Python.h:97,
                 from setools/policyrep.c:52:
/usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
  446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
setools/policyrep.c:92274:3: error: ‘PyUnicode_AsUnicode’ is deprecated [-Werror=deprecated-declarations]
92274 |   __pyx_t_1 = (__pyx_v_self->__pyx_base.rule_string != Py_None)&&(__Pyx_PyUnicode_IS_TRUE(__pyx_v_self->__pyx_base.rule_string) != 0);
      |   ^~~~~~~~~
In file included from /usr/include/python3.9/unicodeobject.h:1026,
                 from /usr/include/python3.9/Python.h:97,
                 from setools/policyrep.c:52:
/usr/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
  580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
      |                                             ^~~~~~~~~~~~~~~~~~~
```

This is because cython generates C code which calls `_PyUnicode_get_wstr_length` and `PyUnicode_AsUnicode` and these functions are "Deprecated since version 3.3, will be removed in version 3.10 [of CPython]." (according to https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_AsUnicode). This issue was reported and fixed in Cython (cf. https://github.com/cython/cython/issues/3724) but this fix is not part of a release yet. More precisely, cython's last release is  0.29.21 and uses the deprecated functions, while the next version (3.0) has been in alpha state since August (according to https://pypi.org/project/Cython/#history).

In setools, adding `-Wno-error=deprecated-declarations` to `setup.py` fixes the issue and makes the build work fine. As I maintain the setools package on the Arch User Repository, I will simply add this option when building the package. Nevertheless you might want to do something such as adding this build flag in the `4.3` branch and releasing a version 4.3.1. This would greatly help package maintainers, even though this is not required.

If you do not want to do fix this issue (which would be completely all right: it is "not your bug"), feel free to close it.

**Comment by pebenito** [comment]
This makes me wonder if, in the long run the extra warning flags are too aggressive since the C code is completely generated.

**Comment by pebenito** [comment]
I think I will drop the -Werror and reduce some of the extra warnings. Since the C code is generated, it's completely dependent on cython. There's not much we can do in setools other than ignore warnings, which is a context-dependent whack-a-mole. The unit tests will continue to be the place to catch problems.

It's almost time for 4.4, so I probably won't be doing a 4.3.1 just for this.
