### ISSUE TITLE
Fails to build with Python 3.8

### ISSUE THREAD

**Issue by mcepl** [SELinuxProject/setools#31]
Build of setools with Python 3.8 fails with

```
[   19s] gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -DOPENSSL_LOAD_CONF -fwrapv -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -fPIC -I/usr/include/python3.8 -c setools/policyrep.c -o build/temp.linux-x86_64-3.8/setools/policyrep.o -Werror -Wextra -Waggregate-return -Wfloat-equal -Wformat -Wformat=2 -Winit-self -Wmissing-format-attribute -Wmissing-include-dirs -Wnested-externs -Wold-style-definition -Wpointer-arith -Wstrict-prototypes -Wunknown-pragmas -Wwrite-strings -Wno-unused-parameter -Wno-suggest-attribute=format -Wno-sign-compare -Wno-cast-qual -Wno-unreachable-code -Wno-implicit-fallthrough -Wno-cast-function-type -fno-exceptions
[   60s] setools/policyrep.c:132881:1: error: missing initializer for field ‘tp_print’ of ‘PyTypeObject’ {aka ‘struct _typeobject’} [-Werror=missing-field-initializers]
[   60s] 132881 | };
[   60s]        | ^
[   60s] In file included from /usr/include/python3.8/object.h:746,
[   60s]                  from /usr/include/python3.8/pytime.h:6,
[   60s]                  from /usr/include/python3.8/Python.h:85,
[   60s]                  from setools/policyrep.c:53:
[   60s] /usr/include/python3.8/cpython/object.h:260:30: note: ‘tp_print’ declared here
[   60s]   260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
[   60s]       |                              ^~~~~~~~
```
(repeated many many times probably for each Python object created)

This has been discussed in many bugs (at least in [bpo#37221](https://bugs.python.org/issue37221), [bpo#37250](https://bugs.python.org/issue37250), and [gh#cython/cython#2938](https://github.com/cython/cython/issues/2938)). However, following these issues, it seems to me that this whole disaster of problems should be resolved with re-Cythonization of the source code (which is done by setools’ ``setup.py``) with Cython >= 0.29.10. However, this code is generated with 0.29.13 and still I can see that there are ``tp_print`` slots in the generated code.

[Generated policyrep.c](https://github.com/SELinuxProject/setools/files/3793710/policyrep.c.txt)

Any idea, what’s going on?

Cc: @scoder, @robertwb

[Full build log](https://github.com/SELinuxProject/setools/files/3793564/_log.txt)

**Comment by pebenito** [comment]
Is this still an issue? The travis-ci builds don't have this problem, for example: https://travis-ci.org/github/SELinuxProject/setools/jobs/663160288#L239

**Comment by mcepl** [comment]
We have [this patch](https://build.opensuse.org/package/view_file/openSUSE:Factory/setools/python3.8-compat.patch?expand=1) in our package, which apparently makes the build pass. [Submit request](https://build.opensuse.org/request/show/744477) which introduced the patch, mentions this bug and necessity to remove ``-Werror``.

**Comment by pebenito** [comment]
The patch you noted doesn't seem to be related to this bug. The suppress removal is curious, since that has been around since Python 3.4. The libraries change seems to be specific to OpenSUSE. Looks like the travis-ci builds have Cython 0.29.15, which may be the fix for this issue.

**Comment by scoder** [comment]
Cython 0.29.14 and later should fix this.
